import discord

STATUSES = [
    discord.Game("Minecraft"),
    discord.Game("Minceraft"),
    discord.Game("Minecraft with garmin"),
    discord.Game("Team Fortress 2"),
    discord.Game("Garry's Mod"),
    discord.Game("Among Us"),
    discord.Game("Balatro"),
    discord.Game("insert high octane game here"),
    discord.Game("cinco noches con alfredo"),
    discord.Game("Spinning Dango Simulator"),
    discord.Game("Hopper Heros"),
    discord.Game("DELTARUNE"),
    discord.Game("Geometry Dash"),
    discord.Game("Jetpack Joyride"),
    discord.Game("LittleBigPlanet 2"),
    discord.Game("Super Mario on the PS4"),
    discord.Game("Boblox"),
    discord.Game("Roblox"),
    discord.Game("Pou"),
    discord.Game("Talking Ben"),
    discord.Game("ODYSEA"),
    discord.Game("Brauser"),
    discord.Game("HOW TO CLOSE TERRARIA?"),
    discord.Game("HOW TO CLOSE VIM?"),
    discord.Activity(type=discord.ActivityType.watching, name="you"),
    discord.Activity(type=discord.ActivityType.watching, name="vsauce (or am i?)"),
    discord.Activity(type=discord.ActivityType.watching, name="NateXS"),
    discord.Activity(type=discord.ActivityType.watching, name="31 Minutos"),
    discord.Activity(type=discord.ActivityType.watching, name="Spongebob Squarepants"),
    discord.Activity(type=discord.ActivityType.watching, name="BFDI"),
    discord.Activity(type=discord.ActivityType.watching, name="Shrek the Third"),
    discord.Activity(type=discord.ActivityType.watching, name="Megamind"),
    discord.Activity(type=discord.ActivityType.watching, name="Bee Movie"),
    discord.Activity(type=discord.ActivityType.watching, name="Cars 2"),
    discord.Activity(type=discord.ActivityType.watching, name="Sonic Movie"),
    discord.Activity(type=discord.ActivityType.watching, name="A Minecraft Movie"),
    discord.Activity(type=discord.ActivityType.watching, name="ASMR Whispering Stock Market Crashes 1929-2020"),
    discord.Activity(type=discord.ActivityType.watching, name="paint dry"),
    discord.Activity(type=discord.ActivityType.watching, name="your browser history"),
    discord.Activity(type=discord.ActivityType.listening, name="White Noise Therapy ASMR"),
    discord.Activity(type=discord.ActivityType.listening, name="weezer"),
    discord.Activity(type=discord.ActivityType.listening, name="NoCopyrightSounds"),
    discord.Activity(type=discord.ActivityType.listening, name="Rick Astley"),
    discord.Activity(type=discord.ActivityType.listening, name="Daft Punk"),
    discord.Activity(type=discord.ActivityType.listening, name="Gorillaz"),
    discord.Activity(type=discord.ActivityType.listening, name="MUSTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARD"),
    discord.Activity(type=discord.ActivityType.listening, name="Eminem"),
    discord.Activity(type=discord.ActivityType.listening, name="Queen"),
    discord.Activity(type=discord.ActivityType.listening, name="Crazy Frog - Axel F"),
    discord.Activity(type=discord.ActivityType.listening, name="Crab Rave"),
    discord.Activity(type=discord.ActivityType.listening, name="Skrillex"),
    discord.Activity(type=discord.ActivityType.listening, name="dr giggletouch"),
    discord.Activity(type=discord.ActivityType.listening, name="dr hankyspanky"),
    discord.Activity(type=discord.ActivityType.listening, name="dj toenail"),
    None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None
]
